# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'claneapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

# Required by RNFirebase
#use_frameworks!
pod 'Firebase/Core', '~> 5.3.0'
pod 'Fabric', '~> 1.7.5'
pod 'Crashlytics', '~> 3.10.4'
pod 'Firebase/DynamicLinks', '~> 5.3.0'
pod 'Firebase/Messaging'
pod 'Firebase/Performance'
# Pods for claneapp


#  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

#  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

#  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

#  pod 'react-native-branch', :path => '../node_modules/react-native-branch'

#  pod 'RNNotificationActions', :path => '../node_modules/react-native-ios-notification-actions'

# pod 'instabug-reactnative', :path => '../node_modules/instabug-reactnative'

  # pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  #pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'

end
